version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/my-app
      args:
        VITE_API_URL: "http://backend:8000"
    ports:
      - "5173:5173"
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
