from app.agents.writing_agent import WritingAgentHandler
from app.agents.conversation_agent import ConversationAgentHandler
from fastapi import APIRouter, Depends
from app.helpers.jwt_token_helper import validate_token
from app.schemas.agent_schema import AgentRequest


agent_router = APIRouter(tags = ["agent"])

@agent_router.post("/writing_agent", dependencies= [Depends(validate_token)])
async def writing_agent(request: AgentRequest) -> str:
    """
    This endpoint processes a user's writing-related request using the WritingAgentHandler.
    It supports tasks such as grammar explanations, sentence examples, corrections, and more.

    Parameters:
    - request (WritingAgentRequest): Includes the user ID and the input question or task.

    Returns:
    - str: The response generated by the writing agent based on the provided input.
    """
    agent = WritingAgentHandler()
    response = await agent.run(user_id = request.user_id, user_input = request.question)
    return response

@agent_router.post("/conversation_agent", dependencies= [Depends(validate_token)])
async def conversation_agent(request: AgentRequest) -> str:
    """
    This endpoint processes a user's conversation-related request using the ConversationAgentHandler.
    It supports tasks such as roleplay conversations, feedback, and more.

    Parameters:
    - request (AgentRequest): Includes the user ID and the input question or task.
    """ 
    agent = ConversationAgentHandler()
    response = await agent.run(user_id = request.user_id, user_input = request.question)
    return response