from writing.agents.writing_agent import WritingAgentHandler
from fastapi import APIRouter, Depends
from writing.helpers.jwt_token_helper import validate_token
from writing.schemas.agent_schema import WritingAgentRequest

agent_router = APIRouter(tags = ["agent"])

@agent_router.post("/writing_agent", dependencies= [Depends(validate_token)])
async def writing_agent(request: WritingAgentRequest) -> str:
    """
    This endpoint processes a user's writing-related request using the WritingAgentHandler.
    It supports tasks such as grammar explanations, sentence examples, corrections, and more.

    Parameters:
    - request (WritingAgentRequest): Includes the user ID and the input question or task.

    Returns:
    - str: The response generated by the writing agent based on the provided input.
    """
    agent = WritingAgentHandler()
    response = await agent.run(user_id = request.user_id, user_input = request.question)
    return response.response.blocks[0].text